import { SHOW_PRICES } from "@/lib/settings";
import Link from "next/link";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { fmtDate, money, prettyReg } from "@/lib/format";

export const dynamic = "force-dynamic";

export default async function BillsPage() {
  const user = await requireUser("/bills");
  const bills = await db.bill.findMany({
    where: { userId: user.id },
    orderBy: { createdAt: "desc" },
    include: { vehicle: true },
  });
  const due = bills.filter((b) => !b.paid).reduce((a, b) => a + b.total, 0);

  return (
    <div className="container page">
      <div className="page-head">
        <div>
          <span className="eyebrow">Billing</span>
          <h1>My bills</h1>
        </div>
        {SHOW_PRICES.customerBills && due > 0 && <div className="badge unpaid" style={{ fontSize: "0.9rem", padding: "8px 14px" }}>Outstanding: {money(due)}</div>}
      </div>
      <div className="table-wrap">
        <table className="tbl">
          <thead>
            <tr><th>Bill</th><th>Date</th><th>Vehicle</th>{SHOW_PRICES.customerBills && <th className="num">Amount</th>}<th>Status</th><th /></tr>
          </thead>
          <tbody>
            {bills.map((b) => (
              <tr key={b.id}>
                <td><b>{b.number}</b></td>
                <td>{fmtDate(b.createdAt)}</td>
                <td>{b.vehicle.make} {b.vehicle.model} <span className="reg">{prettyReg(b.vehicle.regNo)}</span></td>
                {SHOW_PRICES.customerBills && <td className="num mono"><b>{money(b.total)}</b></td>}
                <td><span className={`badge ${b.paid ? "paid" : "unpaid"}`}>{b.paid ? "Paid" : "Due"}</span></td>
                <td className="right"><Link href={`/bills/${b.id}`} className="btn btn-ghost btn-sm">Open</Link></td>
              </tr>
            ))}
            {bills.length === 0 && (
              <tr><td colSpan={SHOW_PRICES.customerBills ? 6 : 5}><div className="empty">No bills yet. Bills generated by the garage for your vehicles appear here.</div></td></tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
